{
  "starting_cash": 500.00,
  "cards": [
    {
      "id": 1,
      "name": "Vladimir Guerrero Jr.",
      "sport": "MLB",
      "set": "2023 Topps Chrome",
      "condition": "NM",
      "price_paid": 45.00,
      "target_sell": "",
      "current_price": 52.00,
      "thesis": "Undervalued Blue Jays star, strong hobby upside",
      "notes": "Numbered /99",
      "sale_date": "",
      "sale_price": "",
      "sale_site": "",
      "pnl": "",
      "status": "active",
      "image_front": "",
      "image_back": ""
    },
    {
      "id": 2,
      "name": "Corbin Carroll",
      "sport": "MLB",
      "set": "2023 Topps Chrome Update",
      "condition": "NM",
      "price_paid": 38.00,
      "target_sell": "",
      "current_price": 44.00,
      "thesis": "Post-hype ROY, undervalued auto with World Series upside",
      "notes": "Auto /150",
      "sale_date": "2026-05-10",
      "sale_price": 58.00,
      "sale_site": "eBay",
      "pnl": "",
      "status": "sold",
      "image_front": "",
      "image_back": ""
    },
    {
      "id": 3,
      "name": "Roman Anthony",
      "sport": "MLB",
      "set": "2025 Bowman Chrome",
      "condition": "NM",
      "price_paid": 42.00,
      "target_sell": "",
      "current_price": 48.00,
      "thesis": "Top Red Sox prospect, raw auto at fair entry before breakout",
      "notes": "Prospect auto, pre-debut",
      "sale_date": "",
      "sale_price": "",
      "sale_site": "",
      "pnl": "",
      "status": "active",
      "image_front": "",
      "image_back": ""
    },
    {
      "id": 4,
      "name": "Jacob Wilson",
      "sport": "MLB",
      "set": "2025 Topps Series 1",
      "condition": "NM-MT",
      "price_paid": 22.00,
      "target_sell": "",
      "current_price": 28.00,
      "thesis": "Overshadowed by Kurtz, elite bat-to-ball skills undervalued",
      "notes": "RC auto",
      "sale_date": "",
      "sale_price": "",
      "sale_site": "",
      "pnl": "",
      "status": "active",
      "image_front": "",
      "image_back": ""
    },
    {
      "id": 5,
      "name": "Connor Bedard",
      "sport": "NHL",
      "set": "2023-24 Upper Deck Young Guns",
      "condition": "NM",
      "price_paid": 110.00,
      "target_sell": "",
      "current_price": 135.00,
      "thesis": "Generational talent, Young Guns RC historically strong long-term holds",
      "notes": "Young Guns RC",
      "sale_date": "",
      "sale_price": "",
      "sale_site": "",
      "pnl": "",
      "status": "active",
      "image_front": "",
      "image_back": ""
    },
    {
      "id": 6,
      "name": "Victor Wembanyama",
      "sport": "NBA",
      "set": "2023-24 Panini Prizm",
      "condition": "NM-MT",
      "price_paid": 95.00,
      "target_sell": "",
      "current_price": 88.00,
      "thesis": "Alien talent, slight dip post-rookie year is buy opportunity",
      "notes": "Silver prizm RC",
      "sale_date": "2026-04-20",
      "sale_price": 115.00,
      "sale_site": "Instagram",
      "pnl": "",
      "status": "sold",
      "image_front": "",
      "image_back": ""
    }
  ]
}
